apiVersion: v1
kind: ConfigMap
metadata:
  name: myconfigmap
data:
  DB_HOST : "mysql"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: manjudbadevops/backend:1.0.0
        envFrom:
        - configMapRef:
            name: myconfigmap

---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: expense
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

